### Получение суммы зарплат сотрудников
GET http://localhost:8080/employee/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней
GET http://localhost:8080/employee/salary/high-salary

### Получение всех сотрудников
GET http://localhost:8080/employee

### Получение сотрудника по id
GET http://localhost:8080/employee/id

###  Создание сотрудника
POST http://localhost:8080/employee/create

###  Редактирование сотрудника
PUT http://localhost:8080/employee/update/id

###  Удаление сотрудника
DELETE http://localhost:8080/employee/delete/{id}

###  Всу сотрудники, зарплата которых выше переданного параметра salary.
GET http://localhost:8080/employee/salaryHigherThan